version: '3'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sportfront.rule=Host(`front.apiproc.site`)"
      - "traefik.http.routers.sportfront.entrypoints=https"
#      - "traefik.http.routers.fastapi.tls.certresolver=ls"
    deploy:
      resources:
        limits:
          memory: 600M      # Hard limit, the container will be killed if it exceeds this
        reservations:
          memory: 300M      # Soft limit, expected memory usage

networks:
  default:
    name: proxynet
    external: true

